variable "billing_account" {}
variable "org_id" {}
variable "region" {}
variable "project_id" {}
variable "target_service_account" {}
variable "cluster_name" {}
variable "subnetwork" {}
variable "ip_range_pods" {}
variable "ip_range_services" {}
variable "default_max_pods_per_node" {}
variable "name" {}
variable "memory_size_mb" {}
variable "enable_apis" {}
variable "cpu_count" {}
variable "name_redis" {}
variable "memory_size_gb" {}
variable "network_name" {}
variable "folder_name" {}
variable "pg_ha_name" {}
variable "pg_ha_external_ip_range" {}
variable "project_name" {}