variable "region" {}
variable "enable_apis" {}
variable "memory_size_mb" {}
variable "project_id" {}
variable "cpu_count" {}
variable "name" {}
variable "network_project_id" {}
variable "network_name" {}
variable "network_self_link" {}