region = "us-west1"
project_id = "projectabcc79e26c4"
target_service_account = "projectabcc79e26c4-sa@projectabcc79e26c4.iam.gserviceaccount.com"
pg_ha_name = "myhapostgres"
pg_ha_external_ip_range = "0.0.0.0/0"